services:
  # Backend API service
  - type: web
    name: blood-donor-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app
    plan: free # Explicitly set to free tier
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "true"

  # Frontend service as a static site (always on in free tier)
  - type: static
    name: blood-donor-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: blood-donor-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
