services:
  # Backend API service
  - type: web
    name: blood-donor-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false

  # Frontend service
  - type: web
    name: blood-donor-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: VITE_API_URL
        fromService:
          name: blood-donor-backend
          type: web
          property: host
          envVarKey: RENDER_EXTERNAL_URL
