name: Deploy to Render

on:
  push:
    branches: [ main ] # Replace with your default branch if not main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }} # You'll need to add this secret in GitHub
          api-key: ${{ secrets.RENDER_API_KEY }} # You'll need to add this secret in GitHub
